Url_Shortener/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shortener.views import URLRedirectView ,HomeView,ViewUrl

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^view_url/',ViewUrl.as_view(),name='view_url'),
    #url(r'^view_analytics/',URLRedirectView.as_view(),name='view_analytics'),
    url(r'^(?P<shortcode>[\w-]+)/$',URLRedirectView.as_view(),name='scode'),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
	login,logout,password_reset,password_reset_done,password_reset_confirm,
	password_reset_complete
	)
urlpatterns = [
	url(r'^home/$',views.home,name='home'),
	url(r'^login/$',login,{'template_name':'accounts/login.html'},name='login'),
	url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
	url(r'^register/$',views.register,name='register'),
	url(r'^profile/$', views.view_profile,name='view_profile'),
	url(r'^profile/edit/$', views.edit_profile,name='edit_profile'),
	url(r'^profile/change-password$', views.change_password,name='change_password'),

	url(r'^reset-password/$', password_reset, {'template_name':'accounts/reset_password.html','post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},name='reset_password'),

	url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/reset_password_done.html'},name='password_reset_done'),

	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{'template_name':'accounts/reset_password_confirm.html','post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

	url(r'^reset-password/complete/$', password_reset_complete,{ 'template_name':'accounts/password_reset_complete.html'},name='password_reset_complete'),
]

shortener/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from shortener.utils import create_shortcode
from .validators import validate_url,validate_dot_com
#from django.core.urlresolvers import reverse
from django_hosts.resolvers import reverse
from django.contrib.auth.models import User

SHORTCODE_MAX=getattr(settings,"SHORTCODE_MAX",15)

class PcURLManager(models.Manager):
	def all(self,*args,**kwargs):
		qs_main= super(PcURLManager,self).all(*args,**kwargs)
		qs=qs_main.filter(active=True)
		return qs

	def refresh_shortcodes(self,items=None):
		qs=PcURL.objects.filter(id__gte=1)
		if items is not None and isinstance(items, int):
			qs=qs.order_by('-id')[:items]
		new_codes=0
		for q in qs:
			q.shortcode = create_shortcode(q)
			print q.id
			q.save()
			new_codes+=1
		return "New codes made: {i}".format(i=new_codes)

class PcURL(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	url=models.CharField(max_length=220,validators=[validate_url,validate_dot_com])
	shortcode=models.CharField(max_length=SHORTCODE_MAX,unique=True,blank=True)
	updated=models.DateTimeField(auto_now=True)
	timestamp=models.DateTimeField(auto_now_add=True)
	active= models.BooleanField(default=True)

	objects=PcURLManager()
	#some_random=PcURLManager()

	def save(self,*args,**kwargs):
		if self.shortcode is None or self.shortcode=="":
			self.shortcode=create_shortcode(self)
		if not "http" in self.url:
			self.url = "http://"+self.url	
		super(PcURL,self).save(*args,**kwargs)

	def __str__(self):
		return str(self.url)

	def __unicode__(self):
		return str(self.url)	

	def get_short_url(self):
		url_path=reverse("scode",kwargs={'shortcode': self.shortcode},host='www',scheme='http',port='8000')
		return url_path

shortener/forms.py
from django import forms
from .validators import validate_url

class SubmitUrlForm(forms.Form):
	url= forms.CharField(
		label='',
		validators=[validate_url],
		widget = forms.TextInput(
			attrs={
				"placeholder":"Long URL",
				"class": "form-control",

			}

			)
		)

	# def clean(self):
	# 	 cleaned_data= super(SubmitUrlForm, self).clean()
	# 	 print cleaned_data
	# 	 url = cleaned_data.get('url')
	
	# def clean_url(self):
	# 	url=self.cleaned_data['url']
	# 	url_validator= URLValidator()
	# 	try:
	# 		url_validator(url)
	# 	except:
	# 		raise forms.ValidationError("Invalid URL for this Field")
	# 	return url		

shortener/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.views import View
from shortener.models import PcURL
from .forms import SubmitUrlForm
from analytics.models import ClickEvent
from django.contrib.auth.models import User

class HomeView(View):
	def get(self,request,*args,**kwargs):
		the_form=SubmitUrlForm()
		context={
			"title":"Url.co",
			"form": the_form
		}
		return render(request,"shortener/home.html",context)

	def post(self,request,*args,**kwargs):
		form=SubmitUrlForm(request.POST)
		context={
				"title":"Url.co",
				"form": form
			}
		template="shortener/home.html"	
		if form.is_valid():
			new_url=form.cleaned_data.get("url")
			#user=UserProfile.objects.filter(user=request.user)
			a=User.objects.get(username=request.user)
			obj,created= PcURL.objects.get_or_create(url=new_url,user=a)
			context={
				"object":obj,
				"created": created,
			}
			if created:
				template="shortener/success.html"
			else:
				template="shortener/already_exists.html"	
		return render(request,template,context)

class URLRedirectView(View): #Class Based View
	def get(self,request,shortcode=None,*args,**kwargs):
		obj=get_object_or_404(PcURL,shortcode=shortcode)
		print ClickEvent.objects.create_event(obj)
		return HttpResponseRedirect(obj.url)

class ViewUrl(View):
	def get(self,request,*args,**kwargs):
		q=PcURL.objects.filter(user=request.user)
		context={
			"object":q
		}
		return render(request,"shortener/view_url.html",context)		

class ViewAnalytics(View):
	def get(self,request,*args,**kwargs):
		q=PcURL.objects.filter(user=request.user)
		context={
			"object":q
		}
		return render(request,"shortener/view_analytics.html",context)		

shortener/templates/base_shortener.html
<!DOCTYPE HTML>
<html>
<head>
<!-- Latest compiled and minified CSS -->
<title>Url.co | {% block title %}Shorten that Url{% endblock title %}</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="http://getbootstrap.com/examples/cover/cover.css" rel="stylesheet">
<style>
body {
	background-color: #226268;
  background-image:url('http://www.desktopwallpaperhd.net/wallpapers/15/7/spitsbergen-norway-mountain-reflections-background-image-travel-wallpaper-150999.jpg');
  background-size: cover; 
}
.btn-link {
  color: #30f;
}
/*.btn-link:hover {
  color: #00000;
}*/
</style>
</head>
<body>

<br>
    <div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
          {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
              <li><a href="{% url 'home' %}">Short_Your_Url</a></li>
              <li><a href="{% url 'accounts:home' %}">Profile</a></li>
              <li><a href="/view_url/">View_Your_Urls</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
              <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
            </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
              </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    </div>

<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="inner cover">
          {% block content %}
			{% endblock content %}
          
          </div>
        </div>

      </div>

    </div>

</body>
</html>