Url_Shortener/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from shortener.views import URLRedirectView ,HomeView,ViewUrl

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name='home'),
    url(r'^view_url/',ViewUrl.as_view(),name='view_url'),
    #url(r'^view_analytics/',URLRedirectView.as_view(),name='view_analytics'),
    url(r'^(?P<shortcode>[\w-]+)/$',URLRedirectView.as_view(),name='scode'),
    url(r'^account/', include('accounts.urls',namespace='accounts')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
	login,logout,password_reset,password_reset_done,password_reset_confirm,
	password_reset_complete
	)
urlpatterns = [
	url(r'^home/$',views.home,name='home'),
	url(r'^login/$',login,{'template_name':'accounts/login.html'},name='login'),
	url(r'^logout/$',logout,{'template_name':'accounts/logout.html'},name='logout'),
	url(r'^register/$',views.register,name='register'),
	url(r'^profile/$', views.view_profile,name='view_profile'),
	url(r'^profile/edit/$', views.edit_profile,name='edit_profile'),
	url(r'^profile/change-password$', views.change_password,name='change_password'),

	url(r'^reset-password/$', password_reset, {'template_name':'accounts/reset_password.html','post_reset_redirect':'accounts:password_reset_done','email_template_name':'accounts/reset_password_email.html'},name='reset_password'),

	url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/reset_password_done.html'},name='password_reset_done'),

	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{'template_name':'accounts/reset_password_confirm.html','post_reset_redirect':'accounts:password_reset_complete'}, name='password_reset_confirm'),

	url(r'^reset-password/complete/$', password_reset_complete,{ 'template_name':'accounts/password_reset_complete.html'},name='password_reset_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class UserProfileManager(models.Manager):
	def get_queryset(self):
		return super(UserProfileManager,self).get_queryset().filter(city='WESTEROS')

class UserProfile(models.Model):
	user = models.OneToOneField(User,to_field='id')
	description= models.CharField(max_length=100, default='')
	city = models.CharField(max_length=100, default='')
	website = models.URLField(default='')
	phone = models.IntegerField(default=0)
	image= models.ImageField(upload_to='profile_image', blank=True)

	objects= UserProfileManager()

	def __str__(self):
		return self.user.username

def create_profile(sender,**kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2',
		)

	def save(self, commit=True):
		user= super(RegistrationForm, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user	

class EditProfileForm(UserChangeForm):

	class Meta:
		model= User
		fields = (
		'email',
		'first_name',
		'last_name',
		)
		exclude = ('password',)

	def clean_password(self):
		return ""

accounts/views.py
from __future__ import unicode_literals
from django.conf import settings
from django.shortcuts import render,redirect,get_object_or_404
from accounts.forms import (
	RegistrationForm,
	EditProfileForm,
)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponse
from accounts.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_save
from django.urls import reverse
# Create your views here.

#@login_required
def home(request):
	return render(request,'accounts/home.html')

def register(request):
	form=RegistrationForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		return redirect(reverse('accounts:home'))
	args={'form':form}
	return render(request,'accounts/reg_form.html',args)

#@login_required
def view_profile(request):
	args={'user': request.user}
	return render(request, 'accounts/profile.html', args)

#@login_required
def edit_profile(request):
	if request.method=='POST':
		form = EditProfileForm(request.POST, instance=request.user)

		if form.is_valid():
			form.save()
			return redirect(reverse('accounts:view_profile' ))

	else:
		form = EditProfileForm(instance=request.user)
		args = {'form': form}
		return render(request,'accounts/edit_profile.html', args)

#@login_required
def change_password(request):
	if request.method=='POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect(reverse('accounts:view_profile' ))
		else:
			return redirect(reverse('accounts:change_password' ))
	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form': form}
		return render(request,'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
	<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
		</form>
		<br> 
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
	<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container-fluid header">
			<div class="container">
			<div class="row">

			<h2>Myadvo</h2>
			<h2>Edit Profile</h2>
			</div>
			</div>
</div>
<div class="container">
	<form method="post">
		{% csrf_token %}
		


			<div class="container-fluid ">
			<div class="container">
			<div class="row">
			<div class="col-md-4 ">
				</div>
			<div class="col-md-4 login">

			<div class="row">
			<div class="col-md-4 color">
			Email
			</div>
			<div class="col-md-8">
			<input type="Email" name="email" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Firstname
			</div>
			<div class="col-md-8">
			<input type="text" name="first_name" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Lastname
			</div>
			<div class="col-md-8">
			<input type="text" name="last_name" value="" class="loginid"> 
			</div>
			</div>


			<div class="row text-center">
			<div class="col-md-4 color">

			</div>
			<div class="col-md-4">
			<input type="submit" name="submit" value="update" class="btn_margin"> 
			</div>
			<div class="col-md-4 color">

			</div>
			</div>	
			</div>
			<div class="col-md-4 "></div>

			</div>
			</div>
			</div>
	</form>
		<br> 
	<div class="container-fluid footer">
	<div class="container">
	<div class="row">
	<h1>www.myadvo.in</h1>

	</div>
	</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block head %}
	<title>Welcome to your Profile</title>
{% endblock %}

{% block body %}
<div class="container" style="color: white;">
    <h1>Home</h1>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid header">
<div class="container">
<div class="row">
<h2>Login</h2>
</div>
</div>
</div>
	<form method="post">
		{% csrf_token %}
		<div class="container-fluid">
<div class="container">
<div class="row">
<div class="col-md-4 ">
	</div>
<div class="col-md-4 login">
<div class="row">
<div class="col-md-4 color">
username
</div>
<div class="col-md-8">
<input type="text" name="username" value="" class="loginid" required>
</div>
</div>
<div class="row">
<div class="col-md-4 color">
password
</div>
<div class="col-md-8">
<input type="password" name="password" value="" class="loginid" required>
</div>
</div>
<div class="row text-center">
<div class="col-md-4 color">

</div>
<div class="col-md-4">
<input type="submit" name="submit" value="login" class="btn_margin btn btn-primary btn-lg active">
</div>
<div class="col-md-4 color">

</div>
</div>
</div>
<div class="col-md-4 "></div>

</div>
</div>
</div>
	</form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="color:white;">
	<p>You have been logged out!</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="color:white;">
	<h1>Password Reset Complete</h1>
	<p>
	</p>
	<a href="{% url 'accounts:login' %}">Log In</a>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block head %}
	<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container" style="color: white;">
	<h1>Profile<h1>
	<p>Username: {{ user }}</p>
	<p>First name: {{ user.first_name }}</p>
	<p>Last name: {{ user.last_name }}</p>
	<p>Email: {{ user.email }}</p>
        <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <img src="{{  user.userprofile.image.url }}" width="240">
</div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{%extends 'base.html' %}
	{% block body %}
	<div class="container">
		<h1>Register</h1>	
		<form method='post'>
			{% csrf_token %}
			<div class="container-fluid">

			<div class="container">
			<div class="row">
			<div class="col-md-2 ">
			</div>
			<div class="col-md-8">
			<div class="navbar navbar-inverse menu menu1">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
			<div class="clearfix"></div>
			<div class="collapse navbar-collapse" id="mynavbar">
			</div>
			</div>
			</div>
			<div class="col-md-2 ">
			</div>
			</div>
			</div>
			</div>


			<div class="container-fluid section">
			<div class="container">
			<div class="row">
			<div class="col-md-4 ">
				</div>
			<div class="col-md-4 login">
			<div class="row">
			<div class="col-md-4 color">
			Username
			</div>
			<div class="col-md-8">
			<input type="text" name="username" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Firstname
			</div>
			<div class="col-md-8">
			<input type="text" name="first_name" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Lastname
			</div>
			<div class="col-md-8">
			<input type="text" name="last_name" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Email
			</div>
			<div class="col-md-8">
			<input type="Email" name="email" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Password
			</div>
			<div class="col-md-8">
			<input type="password" name="password1" value="" class="loginid"> 
			</div>
			</div>
			<div class="row">
			<div class="col-md-4 color">
			Confirm password
			</div>
			<div class="col-md-8">
			<input type="password" name="password2" value="" class="loginid"> 
			</div>
			</div>
			<div class="row text-center">
			<div class="col-md-4 color">

			</div>
			<div class="col-md-4">
			<input type="submit" name="submit" value="Register" class="btn_margin"> 
			</div>
			<div class="col-md-4 color">

			</div>
			</div>	
			</div>
			<div class="col-md-4 "></div>

			</div>
			</div>
			</div>

		</form>
		<div class="container-fluid footer">
		<div class="container">
		<div class="row">
		<h1>www.myadvo.in</h1>

		</div>
		</div>
		</div>
	</div>
	{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
	<div style="color:white;">
        <h1>Password Reset</h1>
        <p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    </div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Reset Password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
	<div style="color: white;">
        <h1>Enter new password</h1>
        <p></p>
    </div>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Reset Password</button>
	</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="color: white;">
	<h1>Password Reset Sent</h1>
	<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

	If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
	</p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using out site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}